// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdqvoqoyvhusbalbgyyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcXZvcW95dmh1c2JhbGJneXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzIyMTQsImV4cCI6MjA2Nzk0ODIxNH0.Q4wWm8ipteLZkm8_rq2wcPEZla1ojiwaKA3Q7CYpLLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});